name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        scp -r . ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.USERNAME }}/node-sample-app/

    - name: Deploy container
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
        cd /home/${{ secrets.USERNAME }}/node-sample-app/
        docker-compose down
        docker-compose build
        docker-compose up -d
        EOF